[pytest]
markers =
    regression: mark a test as regression scenario
    negative: mark a test as negative scenario
    invalid: mark a test as invalid scenario
    asyncio: mark a test as asyncio scenario
