# ********RoostGPT********
"""
Test generated by RoostGPT for test py-flink-small-repo using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___515780ec15
ROOST_METHOD_SIG_HASH=__init___5c3d43c775


Scenario 1: Proper Assignment of Class Attributes
Details:
  TestName: test_init_attribute_assignment
  Description: This test is intended to verify that the __init__ method correctly assigns the provided arguments to the corresponding class attributes.
Execution:
  Arrange: Initialize a new object of the class using the __init__ method, providing appropriate arguments for count, score, and amount.
  Act: No action is required as the method execute during the initialization.
  Assert: Check that the attributes of the object correctly match the values passed during initialization.
Validation:
  This test ensures that inputs are correctly assigned to the respective attributes, which is critical for any further operations or calls that rely on these attributes.

Scenario 2: Check for Proper Assignment with Zero Values
Details:
  TestName: test_init_zero_values_assignment
  Description: This test is intended to verify that the __init__ method correctly handles and assigns attributes even if zero is provided for count, score, or amount.
Execution:
  Arrange: Initialize a new object using __init__ method with zero values for count, score, and amount.
  Act: No action is required as the method execute during the initialization.
  Assert: Confirm that attributes of the object correctly reflect the zero values passed during initialization.
Validation:
  This test ensures that __init__ method can correctly handle and assign zero values, which is crucial for situations where any of these parameters may legitimately be zero as per business logic and requirement.

Scenario 3: Negative Values Assignment
Details:
  TestName: test_init_negative_values_assignment
  Description: This test is to examine that the __init__ method can handle and correctly assign attributes when negative integers are provided for count, score, or amount.
Execution:
  Arrange: Initialize a new object of the class with negative values for count, score, and amount.
  Act: No action is required as this is initialization, where function executes.
  Assert: Verify that the object attributes appropriately represent the negative values passed during initialization.
Validation:
  This test case ensures that the __init__ method can handle and correctly assign negative values, which is crucial in certain business contexts where the values for these parameters can be negative.
"""

# ********RoostGPT********
import pytest
from models import FeatureVector

class Test_FeatureVectorInit:
    @pytest.mark.regression
    def test_init_attribute_assignment(self):
        # Arrange
        proper_count = 5
        proper_score = 10
        proper_amount = 15
        feature_vector = FeatureVector(count=proper_count, score=proper_score, amount=proper_amount)
        
        # Assert
        assert feature_vector.count == proper_count
        assert feature_vector.score == proper_score
        assert feature_vector.amount == proper_amount

    @pytest.mark.regression
    def test_init_zero_values_assignment(self):
        # Arrange
        zero_count = 0
        zero_score = 0
        zero_amount = 0
        feature_vector = FeatureVector(count=zero_count, score=zero_score, amount=zero_amount)
        
        # Assert
        assert feature_vector.count == zero_count
        assert feature_vector.score == zero_score
        assert feature_vector.amount == zero_amount

    @pytest.mark.negative
    def test_init_negative_values_assignment(self):
        # Arrange
        negative_count = -3
        negative_score = -6
        negative_amount = -9
        feature_vector = FeatureVector(count=negative_count, score=negative_score, amount=negative_amount)
        
        # Assert
        assert feature_vector.count == negative_count
        assert feature_vector.score == negative_score
        assert feature_vector.amount == negative_amount
